services:
  cloudflared:
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    container_name: cloudflared
    image: cloudflare/cloudflared:2026.8.0@sha256:2535e54b16adf1d50630f99d0886471926c5ef3f6b328100ec6589f731c48969
    labels:
      - com.smoochy.komodo.restore_stack=cloudflared
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cloudflare-zero-trust.png
    network_mode: host  # Wichtig: Damit Tunnel lokale Services erreicht
    restart: unless-stopped
