services:
  cloudflared:
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    container_name: cloudflared
    image: cloudflare/cloudflared:2026.6.0@sha256:ba461b8aa9c042156dbd39c38657fe7431bafa063220eab8d5330a523863da9f
    labels:
      - com.smoochy.komodo.restore_stack=cloudflared
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/cloudflare-zero-trust.png
    network_mode: host  # Wichtig: Damit Tunnel lokale Services erreicht
    restart: unless-stopped
