services:
  sonarr:
    container_name: sonarr
    deploy:
      resources:
        limits:
          pids: 2048
    environment:
      - HOST_CONTAINERNAME=${SERVICE}
      - HOST_HOSTNAME=homelab-host
      - HOST_OS=Unraid
      - PGID=100
      - PUID=99
      - SONARR_BRANCH=main
      - SONARR_CHANNEL=v4-stable
      - TZ=Europe/Berlin
      - UMASK=022
    image: ghcr.io/linuxserver/sonarr:4.0.17@sha256:3a42a8c298eedf3863ec04a88e0aa7d2ae16e4a9b9e19496f082e38d8bd9d27e
    networks:
      smoonet:
    ports:
      - "8989:8989/tcp"
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sonarr:/config:rw
      - /mnt/user/data:/data:rw
    ## Start Traefik Config
    labels:
      - traefik.enable=true
      # # Internal
      - traefik.http.routers.${SERVICE}-internal.entrypoints=websecure-internal
      - traefik.http.routers.${SERVICE}-internal.middlewares=chain-internal@file
      - traefik.http.routers.${SERVICE}-internal.priority=5000
      - traefik.http.routers.${SERVICE}-internal.rule=Host(`${TRAEFIK_EXTERNAL_URL}`)
      - traefik.http.routers.${SERVICE}-internal.service=${SERVICE}
      - traefik.http.routers.${SERVICE}-internal.tls=true
      # # External
      - traefik.http.routers.${SERVICE}-external.entrypoints=websecure-external
      - traefik.http.routers.${SERVICE}-external.middlewares=chain-external@file
      - traefik.http.routers.${SERVICE}-external.priority=10
      - traefik.http.routers.${SERVICE}-external.rule=Host(`${TRAEFIK_EXTERNAL_URL}`)
      - traefik.http.routers.${SERVICE}-external.service=${SERVICE}
      - traefik.http.routers.${SERVICE}-external.tls=true
      # # HTTP-Header
      - traefik.http.routers.${SERVICE}-bypass.entrypoints=websecure-external
      - traefik.http.routers.${SERVICE}-bypass.middlewares=chain-external-bypass@file
      - traefik.http.routers.${SERVICE}-bypass.priority=2500
      - traefik.http.routers.${SERVICE}-bypass.rule=Host(`${TRAEFIK_EXTERNAL_URL}`) && Header(`${SPECIAL_HEADER_NAME}`, `${SPECIAL_HEADER_SECRET}`)
      - traefik.http.routers.${SERVICE}-bypass.service=${SERVICE}
      - traefik.http.routers.${SERVICE}-bypass.tls=true
      # Service port (must match the port Komodo listens on INSIDE the container)
      - traefik.docker.network=smoonet
      - traefik.http.services.${SERVICE}.loadbalancer.server.url=${TRAEFIK_INTERNAL_URL}
      ## End Traefik Config
      # Komodo restore
      - com.smoochy.komodo.restore_stack=${SERVICE}
      # Unraid metadata
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/sonarr.png
      - net.unraid.docker.webui=${TRAEFIK_INTERNAL_URL}
networks:
  smoonet:
    external: true
