services:
  homebridge:
    container_name: homebridge
    environment:
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - HOST_CONTAINERNAME=homebridge
      - HOST_HOSTNAME=homelab-host
      - HOST_OS=Unraid
      - PGID=100
      - PUID=99
      - TCP_PORT_41808=41808
      - TCP_PORT_8581=8581
      - TZ=Europe/Berlin
      - UMASK=0000
    image: homebridge/homebridge:2026-03-07@sha256:d150c770ec7879b1d277cf162cb104ba5ac4856cd4b887539f0e2c5dfd4c4784
    networks:
      br0:
        ipv4_address: 192.0.2.4
    pids_limit: 2048
    restart: unless-stopped
    volumes:
      - /srv/appdata/homebridge:/homebridge:rw
    ## Start Traefik Config
    labels:
      - traefik.enable=true
      # # Internal
      - traefik.http.routers.${SERVICE}-internal.entrypoints=websecure-internal
      - traefik.http.routers.${SERVICE}-internal.middlewares=chain-internal@file
      - traefik.http.routers.${SERVICE}-internal.priority=5000
      - traefik.http.routers.${SERVICE}-internal.rule=Host(`${TRAEFIK_EXTERNAL_URL}`)
      - traefik.http.routers.${SERVICE}-internal.service=${SERVICE}
      - traefik.http.routers.${SERVICE}-internal.tls=true
      # # External
      - traefik.http.routers.${SERVICE}-external.entrypoints=websecure-external
      - traefik.http.routers.${SERVICE}-external.middlewares=chain-external@file
      - traefik.http.routers.${SERVICE}-external.priority=10
      - traefik.http.routers.${SERVICE}-external.rule=Host(`${TRAEFIK_EXTERNAL_URL}`)
      - traefik.http.routers.${SERVICE}-external.service=${SERVICE}
      - traefik.http.routers.${SERVICE}-external.tls=true
      # # HTTP-Header
      - traefik.http.routers.${SERVICE}-bypass.entrypoints=websecure-external
      - traefik.http.routers.${SERVICE}-bypass.middlewares=chain-external-bypass@file
      - traefik.http.routers.${SERVICE}-bypass.priority=2500
      - traefik.http.routers.${SERVICE}-bypass.rule=Host(`${TRAEFIK_EXTERNAL_URL}`) && Header(`${SPECIAL_HEADER_NAME}`, `${SPECIAL_HEADER_SECRET}`)
      - traefik.http.routers.${SERVICE}-bypass.service=${SERVICE}
      - traefik.http.routers.${SERVICE}-bypass.tls=true
      # Service port (must match the port Komodo listens on INSIDE the container)
      - traefik.docker.network=br0
      - traefik.http.services.homebridge.loadbalancer.server.url=${TRAEFIK_INTERNAL_URL}
      ## End Traefik Config
      - com.smoochy.komodo.restore_stack=homebridge
      - net.unraid.docker.icon=https://raw.githubusercontent.com/homebridge/branding/master/logos/homebridge-color-round-stylized.png
      - net.unraid.docker.webui=${TRAEFIK_INTERNAL_URL}
networks:
  br0:
    external: true
